version: '3'
services:
    hardhat:
        build: .
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        env_file:
            - .env
        ports:
            - "127.0.0.1:8545:8545"
            - "127.0.0.1:8550:8550"
        networks:
            - owlracle
            - hardhat
        command: "npm start"
    slither:
        image: trailofbits/eth-security-toolbox
        volumes:
            - .:/share
            - node_modules:/share/node_modules
        tty: true
        networks:
            - hardhat
volumes:
    node_modules:
networks:
    owlracle:
        external: true
    hardhat:

