version: '3'
services:
    hardhat:
        build: .
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        env_file:
            - .env
        ports:
            - "127.0.0.1:8500-8600:8500-8600"
        command: "npm start"
    slither:
        image: trailofbits/eth-security-toolbox
        volumes:
            - .:/share
            - node_modules:/share/node_modules
        tty: true
volumes:
    node_modules:
